services:
  rimjob:
    image: ghcr.io/lpoyoll/rimjob:latest
    ports:
      - 25555:25555
    volumes:
      - ./Data:/Data
    container_name: rimjob-server
    restart: always
    stdin_open: true
    tty: true
