<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>Rimjob.SharedColony</AssemblyName>
    <RootNamespace>Rimjob.SharedColony</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <OutputPath>../../1.6/Assemblies</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendConfigurationToOutputPath>false</AppendConfigurationToOutputPath>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4633" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RTClient">
      <HintPath>../Assemblies/RTClient.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="RTNetwork">
      <HintPath>../Assemblies/RTNetwork.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="RTShared">
      <HintPath>../Assemblies/RTShared.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
