<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>RTServer</RootNamespace>
		<RuntimeIdentifiers>win-x64;win-x86;linux-x64;linux-arm;linux-arm64</RuntimeIdentifiers>
		<LangVersion>latest</LangVersion>
		<AssemblyTitle>RTServer</AssemblyTitle>
    </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MessagePack" Version="3.1.8" />
		<PackageReference Include="Mono.Nat" Version="3.0.4" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.Security.Permissions" Version="10.0.10" />
    </ItemGroup>

	<ItemGroup>
	  <Reference Include="RTNetwork">
	    <HintPath>..\Assemblies\RTNetwork.dll</HintPath>
	  </Reference>
	  <Reference Include="RTShared">
	    <HintPath>..\Assemblies\RTShared.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>
